#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

. ./scripts/common

mkdir -p dist/artifacts
tar cvJf dist/artifacts/$(basename $BIN)${SUFFIX}.tar.xz -C $(dirname $BIN) .
