#!/bin/bash
set -e

godep go test ./...

if [ ! -e ./bin/rancher-catalog-service ]; then
    ./scripts/build
fi

# Create broken git repo.
./scripts/test-warm



if [ "$CATALOG_URL" = "" ]
then
   CATALOG_URL="rancher=https://github.com/rancher/rancher-catalog.git"
fi


./bin/rancher-catalog-service -catalogUrl ${CATALOG_URL} -port 8088 &
trap "kill $!" exit
cd integration
tox -e flake8,py27
