#!/bin/bash
set -e

# Create broken git repo.
git clone https://github.com/rancher/rancher-catalog.git /tmp/broken-catalog
mkdir -p /tmp/broken-catalog/templates/broken/0
touch /tmp/broken-catalog/templates/broken/0/catalogIcon-broken.png
cat > /tmp/broken-catalog/templates/broken/config.yml <<EOF
name: broken
description: |
  broken
version: 1.1
category: broken
EOF

cat > /tmp/broken-catalog/templates/broken/0/docker-compose.yml <<EOF
web:
  image: nginx
EOF

cat > /tmp/broken-catalog/templates/broken/0/rancher-compose.yml <<EOF
.catalog:
  name: broken
  version: 1.1
  description: |
    broken repo
  minimum_rancher_version: v0.46.0
  uuid: broken-0
  questions:
    variable: "scale"
      description: "Number of broken nodes."
      label: "Number of Nodes:"
      required: true
      default: 3
      type: "int" 
EOF

pushd /tmp/broken-catalog
git config user.email "ci@example.com"
git config user.name "ci"
git add templates/broken/*
git commit -m "test commit"
popd
