#!/bin/bash
set -e

godep go test ./...

if [ ! -e ./bin/rancher-catalog-service ]; then
    ./scripts/build
fi

# Create broken git repo.
./scripts/test-warm

./bin/rancher-catalog-service -catalogUrl https://github.com/rancher/rancher-catalog.git -port 8088 &
trap "kill $!" exit
cd integration
tox -e flake8,py27
